# Generated by Django 5.1.6 on 2025-02-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_alter_post_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
